package view;

import java.awt.event.ItemEvent;

/**
 *
 * @author yonier
 */
public class menu extends javax.swing.JPanel {

    private main main;

    public menu(main main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "Hacer inventario", "Modificar inventario", "Revisar inventario", "Modificar usuarios", "Buscar usuarios", "Eliminar usuarios" }));
        menu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuItemStateChanged(evt);
            }
        });
        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 87, 235, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menusys.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Menu");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (menu.getSelectedIndex() == 5) {
                main.irmostrarUser(this);
            }
        }

    }//GEN-LAST:event_menuItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> menu;
    // End of variables declaration//GEN-END:variables
}
